### ISSUE TITLE
prototype

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos-http#1]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0crat** [comment]
I'm not managing `yegor256/cactoos-http` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#3](https://github.com/yegor256/cactoos-http/issues/3), [#4](https://github.com/yegor256/cactoos-http/issues/4) are still not solved; solved: [#5](https://github.com/yegor256/cactoos-http/issues/5).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#37](https://github.com/yegor256/cactoos-http/issues/37), [#4](https://github.com/yegor256/cactoos-http/issues/4) are still not solved; solved: [#3](https://github.com/yegor256/cactoos-http/issues/3), [#5](https://github.com/yegor256/cactoos-http/issues/5).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#37](https://github.com/yegor256/cactoos-http/issues/37), [#38](https://github.com/yegor256/cactoos-http/issues/38) are still not solved; solved: [#3](https://github.com/yegor256/cactoos-http/issues/3), [#4](https://github.com/yegor256/cactoos-http/issues/4), [#5](https://github.com/yegor256/cactoos-http/issues/5).

**Comment by 0pdd** [comment]
@yegor256 all 5 puzzles are solved here: [#37](https://github.com/yegor256/cactoos-http/issues/37), [#38](https://github.com/yegor256/cactoos-http/issues/38), [#3](https://github.com/yegor256/cactoos-http/issues/3), [#4](https://github.com/yegor256/cactoos-http/issues/4), [#5](https://github.com/yegor256/cactoos-http/issues/5).
