### ISSUE TITLE
HtTimedWire

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos-http#10]
Let's create a `Wire` decorator, which will terminate the connection if it's taking too long.

**Comment by 0crat** [comment]
Job [#10](https://github.com/yegor256/cactoos-http/issues/10) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#10](https://github.com/yegor256/cactoos-http/issues/10) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/941740240); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by victornoel** [comment]
@0crat wait
I need yegor256/cactoos#761 to do this.

**Comment by 0crat** [comment]
> @0crat wait I need yegor256/cactoos#761 to do this. ([here](https://github.com/yegor256/cactoos-http/issues/10#issuecomment-379460259))

@victornoel The impediment for [#10](https://github.com/yegor256/cactoos-http/issues/10) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 the issue is fixed by #35 that was merged

**Comment by victornoel** [comment]
@yegor256 could you please close this issue? it has been fixed by #35.

**Comment by yegor256** [comment]
@victornoel thanks!

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
