### ISSUE TITLE
HtRetryWire

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos-http#11]
Let's create a new `Wire` decorator which will retry to make a connection a few times.

**Comment by 0crat** [comment]
Job [#11](https://github.com/yegor256/cactoos-http/issues/11) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#11](https://github.com/yegor256/cactoos-http/issues/11) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/941743309); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#11](https://github.com/yegor256/cactoos-http/issues/11), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 could we undo this? #27  is the PR that solves this ticket.

**Comment by yegor256** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/yegor256/cactoos-http/issues/11#issuecomment-381620492))

@yegor256 The job [#11](https://github.com/yegor256/cactoos-http/issues/11) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1061439204); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by victornoel** [comment]
@0crat wait for #27 to be reviewed/merged

**Comment by 0crat** [comment]
> @0crat wait for #27 to be reviewed/merged ([here](https://github.com/yegor256/cactoos-http/issues/11#issuecomment-381624374))

@victornoel The impediment for [#11](https://github.com/yegor256/cactoos-http/issues/11) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 #47 was merged, please close this issue :)

**Comment by yegor256** [comment]
@victornoel thanks!

**Comment by elenavolokhova** [comment]
@0crat quality good
