### ISSUE TITLE
HtResponse checkstyle AvoidInlineConditionalsCheck

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#14]
`Checkstyle: src/main/java/org/cactoos/http/HtResponse.java[71]: Avoid inline conditionals. (AvoidInlineConditionalsCheck)`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@VsSekorin thanks, fixed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
