### ISSUE TITLE
HttpResponse PMD.AvoidDuplicateLiterals

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#15]
`/src/test/java/org/cactoos/http/HtResponseTest.java[60-60]: The String literal "HTTP/1.1 200 OK" appears 2 times in this file; the first occurrence is on line 60 (AvoidDuplicateLiterals)`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@VsSekorin thanks, fixed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
