### ISSUE TITLE
Keep-alive header is not supported

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos-http#20]
`Connection: keep-alive` is not supported by wire, client should not close a connection in this case. Also `Keep-alive` response header should be properly handled by this wire, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

**Comment by llorllale** [comment]
@g4s8 I think this is gonna be a tricky one. We'd need to not close that input stream and keep a handle on it.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/20#issuecomment-389171421))

@llorllale Job [#20](https://github.com/yegor256/cactoos-http/issues/20) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#20](https://github.com/yegor256/cactoos-http/issues/20) assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361543397); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by g4s8** [comment]
@VsSekorin right, it has two parameters: timeout and max (requests), but timeout is not same as in `HtTimedWire`, here it indicates how long to keep TCP connection opened. Let see this example:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Keep-Alive: timeout=5, max=1000
```
here server asked client to not close TCP connection for 5 seconds. So if client sends new request to this server not later than 5 seconds it can reuse existing TCP connection to server, but if client sends more than 1000 requests in 5 seconds, it should open new connection to the server. Each new response with `Connection: Keep-Alive` header from this stream should renew connection status.

**Comment by 0crat** [comment]
> @0crat wait #57  ([here](https://github.com/yegor256/cactoos-http/issues/20#issuecomment-391893887))

@VsSekorin The impediment for [#20](https://github.com/yegor256/cactoos-http/issues/20) was registered successfully by @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by VsSekorin** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/20#issuecomment-402197517))

@VsSekorin The user @vssekorin[/z](https://www.0crat.com/u/vssekorin) resigned from [#20](https://github.com/yegor256/cactoos-http/issues/20), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
The job [#20](https://github.com/yegor256/cactoos-http/issues/20) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/bbc0e8e1-8bfa-43eb-9637-6111e9d2f4bf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dgroup** [comment]
@0crat wait as #68 is raised.

**Comment by 0crat** [comment]
> @0crat wait as #68 is raised. ([here](https://github.com/yegor256/cactoos-http/issues/20#issuecomment-451746270))

@dgroup The impediment for [#20](https://github.com/yegor256/cactoos-http/issues/20) was registered successfully by @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#74](https://github.com/yegor256/cactoos-http/issues/74) is still not solved.

**Comment by llorllale** [comment]
@g4s8 PR #68 was merged, can we close this?

**Comment by g4s8** [comment]
@llorllale thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dgroup[/z](https://www.0crat.com/u/dgroup), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#20](https://github.com/yegor256/cactoos-http/issues/20) is now out of scope

**Comment by sereshqua** [comment]
quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#74](https://github.com/yegor256/cactoos-http/issues/74) is solved here.
