### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos-http#22]
Does cactoos-http supports websockets protocol?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@g4s8 no, cactoos-http does not support websockets. That would probably belong to Takes (but even they claim in their README that it won't ever be supported)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@g4s8 ok, gotcha

**Comment by llorllale** [comment]
@yegor256 WDYT? Should it be included in scope? From the looks of the README, it kinda sounds like it shouldn't be?

**Comment by yegor256** [comment]
@llorllale I would suggest to stay away from Websockets. It's a different story, if you ask me. A very different dynamics.

**Comment by llorllale** [comment]
@yegor256 agreed

@g4s8 closing this for now.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@018e5afb-436d-4bfb-b1b6-392e6db0f6b4, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos-http#22] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1421462624, Type: "Close job", Author: "llorllale"
