### ISSUE TITLE
Upgrade mechanism

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos-http#23]
The wire should be able to upgrade connection on `101` status code, e.g. this head
```
HTTP/1.1 101 Switching Protocols
Upgrade: TLS/1.0, HTTP/1.1
```
should switch the wire to https protocol.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#23](https://github.com/yegor256/cactoos-http/issues/23) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/cactoos-http/issues/23) assigned to @icok[/z](https://www.0crat.com/u/icok), here is [why](https://www.0crat.com/footprint/C63314D6Z/950522744); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#23](https://github.com/yegor256/cactoos-http/issues/23), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @icok[/z](https://www.0crat.com/u/icok)

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/cactoos-http/issues/23) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C63314D6Z/1101338419); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/23#issuecomment-385208713))

@pbenety The user @pbenety[/z](https://www.0crat.com/u/pbenety) resigned from [#23](https://github.com/yegor256/cactoos-http/issues/23), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/cactoos-http/issues/23) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222143064); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by paulodamaso** [comment]
@0crat wait for #41 resolution for better wire documentation.

**Comment by 0crat** [comment]
> @0crat wait for #41 resolution for better wire documentation. ([here](https://github.com/yegor256/cactoos-http/issues/23#issuecomment-386919337))

@paulodamaso The impediment for [#23](https://github.com/yegor256/cactoos-http/issues/23) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#61](https://github.com/yegor256/cactoos-http/issues/61) is still not solved.

**Comment by paulodamaso** [comment]
@g4s8 PR #53 merged, please close.

**Comment by g4s8** [comment]
@paulodamaso thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/cactoos-http/issues/23) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
