### ISSUE TITLE
LimitedInputStream

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#28]
We need `LimitedInputSteam` that get bytes until some specific bytes.

- `public BoundedInputStream(final InputStream stream, final Bytes limiter)`
- `public BoundedInputStream(final InputStream stream, final byte[] limiter)`

For example, this can be useful for #4 
Example:
```
new BounedInputStream(
    new InputStreamOf("123456789"),
    new BytesOf("56")
)

> "1234"
```

**Comment by yegor256** [comment]
@VsSekorin any other places where it will be used aside from `Head`?

**Comment by VsSekorin** [comment]
@yegor256 `HtStatus`, for example.

**Comment by yegor256** [comment]
@VsSekorin maybe it's better to just create `Head`, which do this work. And in `HtStatus` just read the entire content, convert to String and then `split()` and take the first line?

**Comment by VsSekorin** [comment]
Yes, and similar solutions can be found in #12 #24 . But these are similar problems that can be solved in different ways.

**Comment by victornoel** [comment]
@VsSekorin see the discussion in #29. Also this issue should also include `LimitedInput` (which may be implemented with a `LimitedInputStream`) to keep the same pattern as the rest of the lib.

**Comment by llorllale** [comment]
@VsSekorin I think we can close this

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
