### ISSUE TITLE
HtBody.java:39-44: The implementation of method stream()...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#3]
The puzzle `1-94e51014` from #1 has to be resolved:

https://github.com/yegor256/cactoos-http/blob/d73f4daa73a68e84cf8fcd3b4bcae00ae017f7fd/src/main/java/org/cactoos/http/HtBody.java#L39-L44

The puzzle was created by Yegor Bugayenko on 04-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#3](https://github.com/yegor256/cactoos-http/issues/3) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1041805967); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by victornoel** [comment]
Reminder to myself: check #24 and #4 which have the same problem

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat waiting for #29 

@yegor256 it's clearly an ARC job to redefine responsibilities of object, so I will need you to ensure this is going the right way, I don't see any sane way to implement HtBody, HtStatus and HtHead separately without lots of duplication, I would prefer to base the three of them on something that is more aware of the peculiarities of an http message.

**Comment by 0crat** [comment]
> @0crat waiting for #29 @yegor256 it's clearly an ARC job to redefine responsibilities of obje... ([here](https://github.com/yegor256/cactoos-http/issues/3#issuecomment-383119395))

@victornoel The impediment for [#3](https://github.com/yegor256/cactoos-http/issues/3) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@llorllale sorry, you are the ARC now, see the comment above.

**Comment by llorllale** [comment]
@victornoel see my comment in #29

**Comment by victornoel** [comment]
@0crat waiting for review of #32

**Comment by 0crat** [comment]
> @0crat waiting for review of #32  ([here](https://github.com/yegor256/cactoos-http/issues/3#issuecomment-383307220))

@victornoel Job [#3](https://github.com/yegor256/cactoos-http/issues/3) is already on hold

**Comment by 0pdd** [comment]
The puzzle `1-94e51014` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#37](https://github.com/yegor256/cactoos-http/issues/37) is still not solved.

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#37](https://github.com/yegor256/cactoos-http/issues/37) is solved here.
