### ISSUE TITLE
Not correct example in Read.me

### ISSUE THREAD

**Issue by strogiyotec** [yegor256/cactoos-http#33]
In first example 

String body = new TextOf(
  new HtBody(
    new HtResponse(
      "http://www.google.com",
      "GET / HTTP/1.1"
    )
  )
).asString();

This code is doesn't compile, as I understood it should be replaced to 

String body = new TextOf(
  new HtBody(
    new HtResponse(
      new HtWire("http://www.google.com"),
      "GET / HTTP/1.1"
    )
  )
).asString();

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@strogiyotec fixed in a7f2fd21c2f0a5fe2f6aaab06855b0d7474dbfb3

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@44dce7c2-22ad-4cad-8774-6b1dcca4c573, thread: BkParallel-8
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
