### ISSUE TITLE
Inefficient use of regexps

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos-http#34]
Following classes: `HtBody`, `HtHead`, `HtHeaders` and `HtStatus` are using `String.split()` which compiles the new line/double new line patterns multiple times.
This can be replaced with e.g. precompiling the `Pattern` and storing it in the class as a constant and later on using `Pattern.split()`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by krzyk** [comment]
@llorllale Closing as there is very small performance increase so it is probably not worth the effort.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
