### ISSUE TITLE
Ignore RegexpMultilineCheck

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#36]
Now all classes do check on CRLF(`\r\n`), but RegexpMultilineCheck requires Unix-like end of line in files. Because of this, it is impossible to work with files. For example, to create a test for large text, as `large-text.txt` in `cactoos`.

I think we should ignore RegexpMultilineCheck in this project.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by krzyk** [comment]
@VsSekorin It is not possible to do it project wise, I would suggest to report a bug in qulice so unix file ending is checked only for specific files (e.g. java, xml, groovy, etc) - similar to FileTabCharacter

**Comment by llorllale** [comment]
@VsSekorin also, why would you need this sort of test?

**Comment by VsSekorin** [comment]
@llorllale This test is no longer needed.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
