### ISSUE TITLE
Lack of documentation of Wire interface and HtWire class.

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos-http#41]
The current documentation about Wire interface and HtWire class is absent; there is no documentation about its logic and how it interacts with other project interfaces.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@paulodamaso regarding "how it interacts with other project interfaces", how can we improve the docs? A wire is a connection between two points (client, server); it sends an Input (provided by you) to the server and returns an Input encapsulating the server's response for you to read.

`HtWire` is just the default wire.

**Comment by llorllale** [comment]
@paulodamaso can we close this?

**Comment by paulodamaso** [comment]
@llorllale I think that we should put this description in `Wire` javadoc, how about that?

**Comment by llorllale** [comment]
@paulodamaso right now `Wire` is just:

```java
/**
 * Wire.
 * @since 0.1
 */
public interface Wire {
    /**
     * Send and read result.
     * @param input The source of data
     * @return The stream to read from
     * @throws IOException If fails
     */
    Input send(Input input) throws IOException;
}
```

How about:

```java
/**
 * The physical connection between two HTTP endpoints.
 * @since 0.1
 */
public interface Wire {
    /**
     * Send an input and return the resulting response.
     * @param input The data to send
     * @return The remote service's response
     * @throws IOException If an I/O error occurs
     */
    Input send(Input input) throws IOException;
}
```

WDYT?

**Comment by llorllale** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@llorllale I think that's good for now, thanks.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
