### ISSUE TITLE
Few configuration issues (for cactoos-http)

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos-http#43]
(This is exactly the same as in https://github.com/yegor256/cactoos/issues/815, I don't know if we need two issues, but the repos are separate so I created this also).

1. `.travis.yml`:
- we don't need `gem install est`  (and do we need xcop?, I don't see it used anywhere)
- script should have `pdd --source=$(pwd) --verbose --file=/dev/null` (just like in .rultor.yml) to catch PDD errors early
- ` mvn clean site -Psite --errors --batch-mode` should be after `mvn clean install ...`

2. `.rultor.yml`:
- `-XX:MaxPermSize=256m` should be removed (it is not used by java 8)
- architects section should have llorllale first (so he will asked by rultor after reviewer does `@rultor merge`)
- `pdd --source=$(pwd) --verbose --file=/dev/null` should be first in the `merge` part (to catch PDD errors early without doing long maven build)
- do we need `sudo gem install --no-rdoc --no-ri xcop`?

And general question, do we deploy the result of `mvn site` anywhere? It is build in both rultor and travis, but I don't know if there is a point in doing two almost full maven builds if we don't put the site anywhere.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk fixed in ac5d2fd75ce5d432927b870f4ada777157a1c865, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
