### ISSUE TITLE
Configure javadoc generation

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos-http#44]
To make sure that we don't make mistakes in javadoc configuration please add a javadoc generation phase to travis and rultor config (it should be before the main build phase):
```
mvn javadoc:javadoc
```

To do this we need to configure the plugin to allow our custom tags (`@checkstyle` and `@todo`), without those right now the javadoc generation fails.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk fixed in 1f8e17a857adae08f47c05645160f412e42da29d, thanks
