### ISSUE TITLE
Inconsistent, non-OO or non-declarative tests should be improved

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos-http#48]
I noticed during my last PR that the quality standards of cactoos-http's tests are not at their best.

In particular we have many different ways of asserting facts depending on the test class:
- `Matchers.equalTo()` or `new EqualTo()` to check equality while most of the time `InputHasContent` or `TextHasString` would be perfect (see also yegor256/cactoos#836).
- assertions on `Map.get` while `Matchers.hasEntry` (or its OO equivalent `IsMapContaining`) could make things more declarative.
- calls to `Scalar.value()` while `SclaraHasValue` could be used.
- we should prefer using the `Matcher`'s class constructor instead of the static factory method from `Matchers`. For example use `new StringEndsWith()` instead of `Matchers.endsWith()`.

I propose to fix this as soon as possible before cactoos-http becomes bigger and it becomes cumbersome to fix all those problems.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel let's follow the same path as in yegor256/cactoos#588

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/48#issuecomment-389202800))

@llorllale Job [#48](https://github.com/yegor256/cactoos-http/issues/48) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by paulodamaso** [comment]
@llorllale I'd like to do this.

**Comment by Vatavuk** [comment]
@0crat wait until https://github.com/llorllale/cactoos-matchers/pull/9#issuecomment-389983655 is merged

**Comment by 0crat** [comment]
> @0crat wait until https://github.com/llorllale/cactoos-matchers/pull/9#issuecomment-389983655 is ... ([here](https://github.com/yegor256/cactoos-http/issues/48#issuecomment-389984820))

@Vatavuk The impediment for [#48](https://github.com/yegor256/cactoos-http/issues/48) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment]
@victornoel please close this issue. It was solved in #58

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#48](https://github.com/yegor256/cactoos-http/issues/48) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
