### ISSUE TITLE
Upgrade qulice to 0.17.3

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos-http#49]
New qulice version brings following important changes:
- removal of `@author` tag (it is prohibited now)
- removal of `@version` tag (it is prohibited now)
- license header should start with `/*` instead of `/**`  - this will fix problem with IntelliJ reporting it as a javadoc that is not attached to any class
- checkstyle validation performance improvement (speedup of ~ 10%)
And few minor formatting changes.

Please upgrade the qulice and fix the new problems found.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/49#issuecomment-389203512))

@llorllale Job [#49](https://github.com/yegor256/cactoos-http/issues/49) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#49](https://github.com/yegor256/cactoos-http/issues/49) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361438918); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by victornoel** [comment]
@llorllale should I also bump `jcabi-parent` to latest (0.49.2 -> 0.49.3)?

**Comment by victornoel** [comment]
@0crat waiting for #55

**Comment by 0crat** [comment]
> @0crat waiting for #55  ([here](https://github.com/yegor256/cactoos-http/issues/49#issuecomment-390396630))

@victornoel The impediment for [#49](https://github.com/yegor256/cactoos-http/issues/49) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by llorllale** [comment]
@victornoel I just looked (not too deeply) at [releases](https://github.com/jcabi/jcabi-parent/releases) for `jcabi-parent` - I don't see anything of real interest added in `0.49.3`, or is there?

**Comment by victornoel** [comment]
@llorllale I didn't see anything particular either, I just noticed it was the version used in cactoos-matchers for example and though it was always best to keep it at the latest version... not really justified :)

**Comment by llorllale** [comment]
@victornoel I think in `cactoos-matchers` I set it to the latest version while I was setting up the project just because it was the latest. It could easily have been `0.49.2` or whatever, so let's not worry about it for now.

**Comment by victornoel** [comment]
@llorllale sure, thanks.

**Comment by 0pdd** [comment]
@krzyk the puzzle [#59](https://github.com/yegor256/cactoos-http/issues/59) is still not solved.

**Comment by victornoel** [comment]
@krzyk #55 was merged, you can now close this issue :)

**Comment by krzyk** [comment]
@victornoel thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#49](https://github.com/yegor256/cactoos-http/issues/49) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
