### ISSUE TITLE
HtStatus.java:37-40: The implementation here is not...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#5]
The puzzle `1-6a67a5c8` from #1 has to be resolved:

https://github.com/yegor256/cactoos-http/blob/c677dd9f66707b0aa8d5fabbc33cce80bf846d1e/src/test/java/org/cactoos/http/HtStatus.java#L37-L40

The puzzle was created by Yegor Bugayenko on 04-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#5](https://github.com/yegor256/cactoos-http/issues/5) assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/941260377); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by VsSekorin** [comment]
@0crat wait codereview #12

**Comment by 0crat** [comment]
> @0crat wait codereview #12 ([here](https://github.com/yegor256/cactoos-http/issues/5#issuecomment-378646052))

@VsSekorin The impediment for [#5](https://github.com/yegor256/cactoos-http/issues/5) was registered successfully by @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0pdd** [comment]
The puzzle `1-6a67a5c8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vssekorin[/z](https://www.0crat.com/u/vssekorin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#5](https://github.com/yegor256/cactoos-http/issues/5) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
