### ISSUE TITLE
HtAutoRedirect

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos-http#6]
Let's create `HtAutoRedirect`, which will encapsulate `HtResponse` and make another request if its status code is 30x:

```java
String body = new TextOf(
  new HtBody(new HtAutoRedirect(new HtResponse("http://www.google.com")))
).asString();
```

**Comment by 0crat** [comment]
Job [#6](https://github.com/yegor256/cactoos-http/issues/6) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#6](https://github.com/yegor256/cactoos-http/issues/6) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/941289049); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@yegor256 This issue is solved in #26, please close it.

**Comment by Vatavuk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@Vatavuk thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#6](https://github.com/yegor256/cactoos-http/issues/6) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-8
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-8
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoWriteException: quota exceeded
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-8
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-8
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoWriteException: quota exceeded
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos-http/issues/6#issuecomment-386111084))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by elenavolokhova** [comment]
@yegor256 Could you please take a look at this? 0crat doesn't accept my review here.

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/6#issuecomment-386290881))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#6](https://github.com/yegor256/cactoos-http/issues/6) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%236%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@elenavolokhova no review required here, forget it

**Comment by Vatavuk** [comment]
@yegor256 what about my points?

**Comment by yegor256** [comment]
@Vatavuk I'm araid we lost them :( Due to technical issue we didn't create the QA review properly and the inormation about the task is lost.
