### ISSUE TITLE
HtWire.java:46-49: HtWire should not close the socket...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#63]
The puzzle `62-ec9a5ea7` from #62 has to be resolved:

https://github.com/yegor256/cactoos-http/blob/795e57c6d3c16283c56b66c62a765f5605aadd7d/src/main/java/org/cactoos/http/HtWire.java#L46-L49

The puzzle was created by George Aristy on 28-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#63](https://github.com/yegor256/cactoos-http/issues/63) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#63](https://github.com/yegor256/cactoos-http/issues/63) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/5fa3abb4-e5c8-435c-b928-78b5c8ebeb26); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/63#issuecomment-474141560))

@llorllale The user @borysfan[/z](https://www.0crat.com/u/borysfan) resigned from [#63](https://github.com/yegor256/cactoos-http/issues/63), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#63](https://github.com/yegor256/cactoos-http/issues/63) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/87cae90c-0b6d-4f9d-978f-b383a7806ff0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #76 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #76 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/63#issuecomment-475963945))

@victornoel The impediment for [#63](https://github.com/yegor256/cactoos-http/issues/63) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `62-ec9a5ea7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#78](https://github.com/yegor256/cactoos-http/issues/78) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#63](https://github.com/yegor256/cactoos-http/issues/63) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
The job [#63](https://github.com/yegor256/cactoos-http/issues/63) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/yegor256/cactoos-http/issues/87) is still not solved; solved: [#78](https://github.com/yegor256/cactoos-http/issues/78).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99) are still not solved; solved: [#78](https://github.com/yegor256/cactoos-http/issues/78), [#87](https://github.com/yegor256/cactoos-http/issues/87).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#98](https://github.com/yegor256/cactoos-http/issues/98) is still not solved; solved: [#78](https://github.com/yegor256/cactoos-http/issues/78), [#87](https://github.com/yegor256/cactoos-http/issues/87), [#99](https://github.com/yegor256/cactoos-http/issues/99).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#78](https://github.com/yegor256/cactoos-http/issues/78), [#87](https://github.com/yegor256/cactoos-http/issues/87), [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99).
