### ISSUE TITLE
Update jcabi-parent to 0.49.4 (solves xcop issue)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos-http#71]
Let's update to new jcabi version (0.49.4) because this new version solves xcop issue on windows.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx done in a10575851b39b2d8de4bccb269744ebd8490477f

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos-http#71` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
