### ISSUE TITLE
Update cactoos to 0.39

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/cactoos-http#72]
This is just a marker issue to update cactoos to 0.39.
It's not a minor change, since new version of cactoos introduces lots of checked exceptions to the method signatures for some reason.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/yegor256/cactoos-http/issues/72#issuecomment-459971775))

@llorllale The job [#72](https://github.com/yegor256/cactoos-http/issues/72) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/85e3f72e-bd1c-46af-ac62-3e903fa3a142); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #73

**Comment by victornoel** [comment]
@ilyakharlamov you can now close this issue, the PR (#73) has been merged :)

**Comment by 0crat** [comment]
The job [#72](https://github.com/yegor256/cactoos-http/issues/72) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
