### ISSUE TITLE
BoundedByteBuffer.java:79-81: Figure out a more elegant...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#77]
The puzzle `60-6fe1be4f` from #60 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/f7cf70c0744c750da9a55c97cb485933a878f9d9/src/main/java/org/cactoos/http/io/BoundedByteBuffer.java#L79-L81

The puzzle was created by golyalpha on 26-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#77](https://github.com/yegor256/cactoos-http/issues/77) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#77](https://github.com/yegor256/cactoos-http/issues/77) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/881daffc-6e54-4fe6-bf74-ca4015a4752c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/cactoos-http/pull/85 to be merged.

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos-http/pull/85 to be merged. ([here](https://github.com/yegor256/cactoos-http/issues/77#issuecomment-488653476))

@vzurauskas The impediment for [#77](https://github.com/yegor256/cactoos-http/issues/77) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0pdd** [comment]
The puzzle `60-6fe1be4f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#77](https://github.com/yegor256/cactoos-http/issues/77) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)
