### ISSUE TITLE
HtWireTest.java:103-106: HtWire should not close the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#78]
The puzzle `63-d518e687` from #63 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/52e8b09f716b3cbfb1089a794c61435d768782cf/src/test/java/org/cactoos/http/HtWireTest.java#L103-L106

The puzzle was created by Victor Noël on 24-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#78](https://github.com/yegor256/cactoos-http/issues/78) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#78](https://github.com/yegor256/cactoos-http/issues/78) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/ff85854c-ed1f-447d-94b5-e8b208136741); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #86 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #86 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/78#issuecomment-490518877))

@victornoel The impediment for [#78](https://github.com/yegor256/cactoos-http/issues/78) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `63-d518e687` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/yegor256/cactoos-http/issues/87) is still not solved.

**Comment by 0crat** [comment]
Job [#78](https://github.com/yegor256/cactoos-http/issues/78) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#78](https://github.com/yegor256/cactoos-http/issues/78) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#78](https://github.com/yegor256/cactoos-http/issues/78) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99) are still not solved; solved: [#87](https://github.com/yegor256/cactoos-http/issues/87).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#98](https://github.com/yegor256/cactoos-http/issues/98) is still not solved; solved: [#87](https://github.com/yegor256/cactoos-http/issues/87), [#99](https://github.com/yegor256/cactoos-http/issues/99).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#87](https://github.com/yegor256/cactoos-http/issues/87), [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99).
