### ISSUE TITLE
HtAutoClosedResponseTest.java:40-45: Introduce...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#80]
The puzzle `64-afac576d` from #64 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/9c2c0c7573defa019a5f63c09f2d5023d0e6272f/src/test/java/org/cactoos/http/HtAutoClosedResponseTest.java#L40-L45

The puzzle was created by Victor Noel on 19-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#80](https://github.com/yegor256/cactoos-http/issues/80) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#80](https://github.com/yegor256/cactoos-http/issues/80) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/be085502-0159-49c1-b0cc-707674dce65e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat waiting for #78 to be solved first

**Comment by 0crat** [comment]
> @0crat waiting for #78 to be solved first ([here](https://github.com/yegor256/cactoos-http/issues/80#issuecomment-497320994))

@victornoel The impediment for [#80](https://github.com/yegor256/cactoos-http/issues/80) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat wait for #88 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #88 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/80#issuecomment-498357140))

@victornoel Job [#80](https://github.com/yegor256/cactoos-http/issues/80) is already on hold

**Comment by 0pdd** [comment]
The puzzle `64-afac576d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#80](https://github.com/yegor256/cactoos-http/issues/80) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
The job [#80](https://github.com/yegor256/cactoos-http/issues/80) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
