### ISSUE TITLE
'Get' class is in wrong package

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/cactoos-http#83]
[Get](https://github.com/yegor256/cactoos-http/blob/master/src/test/java/org/cactoos/http/Get.java) class is in `test` package now. Shouldn't it be in `main`?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@vzurauskas was sort of considering #21 but let's move it in this task

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/83#issuecomment-491106131))

@llorllale Job [#83](https://github.com/yegor256/cactoos-http/issues/83) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0crat** [comment]
The job [#83](https://github.com/yegor256/cactoos-http/issues/83) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/C63314D6Z/39f4d27d-86d4-4baa-8b04-9719de9b4245); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for PR #91

**Comment by 0crat** [comment]
> @0crat waiting for PR #91 ([here](https://github.com/yegor256/cactoos-http/issues/83#issuecomment-503647141))

@scristalli The impediment for [#83](https://github.com/yegor256/cactoos-http/issues/83) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by scristalli** [comment]
@vzurauskas PR #91 has been merged, can we close this?
Now `Get` is in the `main` package, along with a test case and a fix on the format of the request.

**Comment by vzurauskas** [comment]
@scristalli Closed.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#83](https://github.com/yegor256/cactoos-http/issues/83) is now out of scope

**Comment by 0crat** [comment]
Job [#83](https://github.com/yegor256/cactoos-http/issues/83) is pending quality review, can't start a new order

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
