### ISSUE TITLE
HtTimedWireTest.java:79-81: With #78 solved, HtWire...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#87]
The puzzle `78-e9bc29cd` from #78 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/ee31a17fb026abf92c23203758ee048adb4deede/src/test/java/org/cactoos/http/HtTimedWireTest.java#L79-L81

The puzzle was created by @rultor on 01-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#87](https://github.com/yegor256/cactoos-http/issues/87) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#87](https://github.com/yegor256/cactoos-http/issues/87) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/C63314D6Z/c4c6868e-59fe-459b-8262-eb3801e10993); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/87#issuecomment-504096236))

@scristalli The user @scristalli[/z](https://www.0crat.com/u/scristalli) resigned from [#87](https://github.com/yegor256/cactoos-http/issues/87), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
The job [#87](https://github.com/yegor256/cactoos-http/issues/87) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/bb1ea1d0-e379-45a9-9e8d-eeae6fe1ad18); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by aivinog1** [comment]
@0crat wait #92

**Comment by 0crat** [comment]
> @0crat wait #92 ([here](https://github.com/yegor256/cactoos-http/issues/87#issuecomment-506200122))

@aivinog1 The impediment for [#87](https://github.com/yegor256/cactoos-http/issues/87) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
The job [#87](https://github.com/yegor256/cactoos-http/issues/87) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/601431b9-fecd-409d-b8f6-b780d2293dd7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #93 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #93 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/87#issuecomment-513479345))

@victornoel The impediment for [#87](https://github.com/yegor256/cactoos-http/issues/87) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `78-e9bc29cd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#87](https://github.com/yegor256/cactoos-http/issues/87) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by WhimsySoftware** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#98](https://github.com/yegor256/cactoos-http/issues/98) is still not solved; solved: [#99](https://github.com/yegor256/cactoos-http/issues/99).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99).
