### ISSUE TITLE
Travis build fails installing oraclejdk8

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos-http#89]
Affects PR #88 

Error:
```
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```
[Build log](https://travis-ci.org/yegor256/cactoos-http/builds/546330302?utm_source=github_status&utm_medium=notification)

**Probable cause**
* Gradual rollout of Xenial as the new [default linux Travis CI build environment](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).
* [oraclejdk8 is not preinstalled in Xenial](https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support) and therefore does not work
* advice from support seems to be to either [use trusty or use a newer **openjdk**](https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345/7)

**Corrective actions**
* Switch to openjdk8 as stopgap
* Switch to the newer openjdks afterwards (does the tooling work?? CI, qulice, etc)

**Comment by llorllale** [comment]
@0crat assign me

**Comment by llorllale** [comment]
@llorllale fixed in 10e6bf4e907b6dbb43d3efd896983c09c2e68439

build log: https://travis-ci.org/yegor256/cactoos-http/builds/546523321

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos-http/issues/89#issuecomment-502496617))

@llorllale The job [#89](https://github.com/yegor256/cactoos-http/issues/89) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/9da14e90-901d-4828-91f4-9fdc92f5564d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#89](https://github.com/yegor256/cactoos-http/issues/89) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
