### ISSUE TITLE
HtContentType

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos-http#9]
Let's create a reader of response `content-type`:

```java
Scalar<String> type = new HtContentType(
  new HtHead(new HtResponse("http://www.google.com"))
).value();
```

**Comment by 0crat** [comment]
Job [#9](https://github.com/yegor256/cactoos-http/issues/9) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#9](https://github.com/yegor256/cactoos-http/issues/9) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/941738160); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by victornoel** [comment]
@yegor256 do we consider that no `content-type` present means `HtContentType` returns an empty `String `?

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#9](https://github.com/yegor256/cactoos-http/issues/9), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos-http#9` is not assigned, can't get performer

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 I was waiting for #18 to be merged and forgot to tell @0crat to wait, is there anything I can do?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos-http/issues/9#issuecomment-381347549); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by yegor256** [comment]
@0crat hey

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c574d3b-2d82-4cad-8b3e-d36ca09cec78, thread: BkParallel-4
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c574d3b-2d82-4cad-8b3e-d36ca09cec78, thread: BkParallel-4
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/9#issuecomment-381663063))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#9](https://github.com/yegor256/cactoos-http/issues/9) is [in scope](http://www.zerocracy.com/policy.html#14) for 12days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%239%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/yegor256/cactoos-http/issues/9#issuecomment-381664935))

@yegor256 Hey, what's up, how is it going?

**Comment by yegor256** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/yegor256/cactoos-http/issues/9#issuecomment-382043226))

@yegor256 The job [#9](https://github.com/yegor256/cactoos-http/issues/9) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1071550009); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by victornoel** [comment]
@0crat wait for #18 to be reviewed/merged

**Comment by 0crat** [comment]
> @0crat wait for #18 to be reviewed/merged ([here](https://github.com/yegor256/cactoos-http/issues/9#issuecomment-382044334))

@victornoel The impediment for [#9](https://github.com/yegor256/cactoos-http/issues/9) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 or @llorllale please close this issue, it has been solved by #18.

**Comment by victornoel** [comment]
@yegor256 issue is solved (by #18 which was merged)

**Comment by yegor256** [comment]
@victornoel thanks

**Comment by elenavolokhova** [comment]
@victornoel According to our Policy:
>Messages in a job always start with a name of a user they are addressed to

This message was not addressed:
> Should be fixed via #18 if we consider that not content type fails the execution.
If we are unsure I can add a todo :)

Please, confirm that you'll try to follow this rule in future.

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
