### ISSUE TITLE
Change project ARC

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos-http#96]
Project ARC needs to be changed in rultor configurations, I can't do merges

**Comment by llorllale** [comment]
@paulodamaso done in 3252fddbec2500a5a55b731c3b9d59ee6f19c388

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos-http#96` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@llorllale Thank you!
