### ISSUE TITLE
BlockingSocketServer.java:45-52: Rework the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#98]
The puzzle `87-b84e58fc` from #87 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/701b89abe5091867180d68a86ff29a5e8183bb29/src/test/java/org/cactoos/http/io/BlockingSocketServer.java#L45-L52

The puzzle was created by @rultor on 21-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#98](https://github.com/yegor256/cactoos-http/issues/98) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/cactoos-http/issues/98) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/b8861bcc-1661-483a-84d9-a0af5826ee66); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by iakunin** [comment]
@victornoel @paulodamaso I cannot reproduce the problem with rultor-build (https://www.rultor.com/t/20323-537729119) locally. 

I unignored the tests and run the same command in the same docker-image
```
docker run --tty --interactive --workdir=/main --volume=${PWD}:/main --rm yegor256/java8 "mvn clean install -Pqulice --errors"
```
and this build successfully passed. The full build log is [here](https://gist.github.com/iakunin/44b0d6d74931cba3f02d4fd192401126).

Maybe we can try to unignore the ignored tests and try to build rultor one more time?

**Comment by iakunin** [comment]
@0crat wait for https://github.com/yegor256/cactoos-http/issues/98#issuecomment-545112402 to be answered.

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos-http/issues/98#issuecomment-545112402 to be a... ([here](https://github.com/yegor256/cactoos-http/issues/98#issuecomment-545112563))

@iakunin The impediment for [#98](https://github.com/yegor256/cactoos-http/issues/98) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by iakunin** [comment]
@0crat wait for https://github.com/yegor256/cactoos-http/pull/101 to be merged

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos-http/pull/101 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/98#issuecomment-552088137))

@iakunin Job [#98](https://github.com/yegor256/cactoos-http/issues/98) is already on hold

**Comment by 0pdd** [comment]
The puzzle `87-b84e58fc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/cactoos-http/issues/98) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)
