### ISSUE TITLE
BlockingSocketServer.java:98-100: Update cactoos to at...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#99]
The puzzle `87-6a44baaf` from #87 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/701b89abe5091867180d68a86ff29a5e8183bb29/src/test/java/org/cactoos/http/io/BlockingSocketServer.java#L98-L100

The puzzle was created by @rultor on 21-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#99](https://github.com/yegor256/cactoos-http/issues/99) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#99](https://github.com/yegor256/cactoos-http/issues/99) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/275faa96-a591-460f-9240-fe53b11fe621); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by iakunin** [comment]
@0crat wait for https://github.com/yegor256/cactoos-http/pull/100 to be merged

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos-http/pull/100 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545089096))

@iakunin The impediment for [#99](https://github.com/yegor256/cactoos-http/issues/99) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by iakunin** [comment]
There is no label "waiting". Trying one more time.

@0crat wait for https://github.com/yegor256/cactoos-http/pull/100 to be merged

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396144); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by iakunin** [comment]
@0crat wait for #100 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #100 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396374))

@iakunin Job [#99](https://github.com/yegor256/cactoos-http/issues/99) is already on hold

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-546856481))

@g4s8 This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#99](https://github.com/yegor256/cactoos-http/issues/99) is [in scope](http://www.zerocracy.com/policy.html#14) for 8days
  * The role is `DEV`
  * The job is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%2399%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by iakunin** [comment]
@0crat wait for #100 to be merged

**Comment by iakunin** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat wait for #100 to be merged ([here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-551398743))

@iakunin Job [#99](https://github.com/yegor256/cactoos-http/issues/99) is already on hold

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-551398774))

@iakunin This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#99](https://github.com/yegor256/cactoos-http/issues/99) is [in scope](http://www.zerocracy.com/policy.html#14) for 18days
  * The role is `DEV`
  * The job is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin) for [17days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%2399%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `87-6a44baaf` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#99](https://github.com/yegor256/cactoos-http/issues/99) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@iakunin please make sure you start all the comments with the name of the user they are addressed to, [see](https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396144)

**Comment by iakunin** [comment]
@sereshqua could you specify which particular comment I should’ve started with the name of the user?

If you’re mean the https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396144
this comment addressed to 0crat. And that’s my bad, that I didn’t start it with the name of the user. But the next comment is pretty correct: https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396374

**Comment by sereshqua** [comment]
@iakunin i gave you the link in my previous comment, you need to start ALL the comment with the name of the user they are addressed to

Policy: 

> Messages in a job always start with a name of a user they are addressed to;

**Comment by iakunin** [comment]
@sereshqua got it, thank you. Next time I’ll pay attention to it

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)
